/laser:
  use_preset: "hokuyo_driver.yaml"
  use_if:
    base_type: pmb2
    laser_model: hokuyo
  ros__parameters:
    serial_port: /dev/ttyACM0
    laser_frame_id: "base_laser_link"
    angle_min: -1.65806
    angle_max: 1.65806
  remappings:
    scan: "/scan_raw"
