/lifecycle_manager_laser_sim:
  use_preset: "lifecycle_manager.yaml"
  use_if:
    base_type: pmb2
  ros__parameters:
    node_names:
      [
        "pal_laser_filters",
        "direct_laser_odometry",
      ]
